FROM nginx:alpine
 
COPY ./infra/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY ./infra/nginx/conf.d/.htpasswd /etc/nginx/conf.d/.htpasswd
 
WORKDIR /var/www/html/public

COPY ./src/public .
